name: Next.js CI/CD
on:
  push:
    tags: v*
  workflow_dispatch:
  # This workflow is reused by multiple workflow triggers:
  # https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow
permissions:
  id-token: write
  pull-requests: write
  contents: read
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: 'refs/heads/main'
        
      - name: Setup JFrog CLI for SAAS main
        uses: jfrog/setup-jfrog-cli@v4
        id: setup-cli-main
        env:  
          JF_URL: https://incloudmaster.jfrog.io
        with:
          oidc-provider-name: manoj-git
          oidc-audience: manoj

      # Step 2: Set the pnpm store path and save as env var for following steps
      - name: Set and get pnpm store directory
        run: |
          pnpm config set store-dir .pnpm-store
          export STORE_PATH=$(pnpm store path --silent)
          echo "STORE_PATH=${STORE_PATH}" >> $GITHUB_ENV
          mkdir -p "${STORE_PATH}"
          ls -la "${STORE_PATH}"
