name: Setup JFrog CLI with OIDC

on: 
  push:
    tags:
      - "v*" # This triggers the workflow on tags that start with "v"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://hts2.jfrog.io/
        with:
          version: '2.73.0'
          oidc-provider-name: manu-oidc-test
          oidc-audience: oidctest

      - name: Generate and Configure JFrog CLI with OIDC
        id: configure-jfrog-cli
        env:
          JFROG_URL: ${{ secrets.JFROG_URL }}
        run: |
          echo "Configuring JFrog CLI with OIDC..."

          # Request GitHub OIDC token and set it as an environment variable
          token=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          $ACTIONS_ID_TOKEN_REQUEST_URL | jq -r '.value')

          # Configure JFrog CLI using the token
          echo "Setting JFrog CLI configuration"
          jf c add my-artifactory-server --url=$JFROG_URL --access-token=$token --interactive=false

      - name: Run JFrog CLI
        run: |
          # Ping the server to check the connection
          jf rt ping --server-id my-artifactory-server
