name: oidc-poc

on:
  push:
    branches:
      - '*'  # This triggers the workflow on any push to any branch

jobs:
  auth:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get id token
        run: |
          ID_TOKEN=$(curl -sLS -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=manoj-test" | jq .value | tr -d '"')
          echo "ID_TOKEN=${ID_TOKEN}" >> $GITHUB_ENV

      - name: Exchange token with access
        env:
          ID_TOKEN: ${{ env.ID_TOKEN }}
          JFROG_PLATFORM_URL: https://hts2.jfrog.io
        run: |
          ACCESS_TOKEN=$(curl -XPOST -H "Content-Type: application/json" "${JFROG_PLATFORM_URL}/access/api/v1/oidc/token" -d "{\"grant_type\": \"urn:ietf:params:oauth:grant-type:token-exchange\", \"subject_token_type\":\"urn:ietf:params:oauth:token-type:id_token\", \"subject_token\": \"${ID_TOKEN}\", \"provider_name\": \"manoj-git\"}" | jq .access_token | tr -d '"')
          echo "ACCESS_TOKEN=${ACCESS_TOKEN}" >> $GITHUB_ENV

      - uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://hts2.jfrog.io
        with:
          oidc-provider-name: manoj-git
          oidc-audience: manoj-test

      - name: Configure JFrog CLI with OIDC
        env:
          JFROG_URL: https://hts2.jfrog.io
          ACCESS_TOKEN: ${{ env.ACCESS_TOKEN }}
        run: |
          echo "Configuring JFrog CLI with access token..."
          
          # Debugging: Output the token length for troubleshooting
          echo "Access token length: ${#ACCESS_TOKEN}"
          
          # If token is empty, fail the step
          if [ -z "$ACCESS_TOKEN" ]; then
            echo "Access token is empty"; exit 1;
          fi
          
          # Configure JFrog CLI with the obtained access token
          jf c add my-artifactory-server \
            --url=$JFROG_URL \
            --access-token=$ACCESS_TOKEN \
            --interactive=false

      - name: Run JFrog CLI
        run: |
          # Ping the server to check the connection
          jf rt ping --server-id my-artifactory-server
